### ISSUE TITLE
Failed to start the kernel (xeus-python 0.15.9)

### ISSUE THREAD

**Issue by benbovy** [jupyterlite/xeus-python-kernel#130]
## Description

Not sure this is the right place to report it, but the very recent deployments of jupyterlite + xeus-python-kernel (last version: 0.15.9) on RTD did not work for me. Jupyterlite is built and deployed without error but the xeus python kernel fails to start when visiting the web page (see browser output below).

## Reproduce

Links to a deployment that is not working (using xeus-python 0.15.9):

- build logs: https://readthedocs.org/projects/ipytone/builds/20334811/
- web page: https://ipytone--112.org.readthedocs.build/en/112/demo.html

Links to a deployment that is working (pinning xeus-python <=0.15.7):

- PR: https://github.com/benbovy/ipytone/pull/114
- build logs: https://readthedocs.org/projects/ipytone/builds/20355311/
- web page: https://ipytone--114.org.readthedocs.build/en/114/demo.html

## Expected behavior

No error when the xeus kernel is initialized.

## Context

- JupyterLite version: 0.1.0
- Operating System and version: MacOS
- Browser and version: Firefox 112.0.2 and Chrome 112.0.5615.137

<details><summary>Browser Output</summary>
<pre>

The relevant console logs:

<img width="666" alt="Screenshot 2023-05-02 at 10 42 47" src="https://user-images.githubusercontent.com/4160723/235621505-1b7dd75a-2a46-4943-99a7-496586406a0f.png">

The error is raised here:

<img width="531" alt="Screenshot 2023-05-02 at 10 43 16" src="https://user-images.githubusercontent.com/4160723/235621519-005c9e5a-0fc4-4212-8155-d8412c3d168c.png">
</pre>
</details>

**Comment by martinRenou** [comment]
Thanks! I am releasing jupyterlite-xeus-python right now with https://github.com/jupyterlite/xeus-python-kernel/pull/129 which should fix the immediate issue.

The underlying issue is that the latest xeus-python version needs empack v3, which jupyterlite-xeus-python does not use. We'll update soon jupyterlite-xeus-python to empack v3, but from now on jupyterlite-xeus-python would always pull a version of xeus-python that works for sure.

**Comment by benbovy** [comment]
Excellent thanks!
