### ISSUE TITLE
Add minimal example of installing package via config file to demo site

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/xeus-python-kernel#82]
It would be really useful if there was a minimum viable example of adding the [`xeus-python-kernel`](https://github.com/jupyterlite/xeus-python-kernel) to the JupyterLite demo site, along with an example of pre-installing two custom packages into the kernel.

**Comment by martinRenou** [comment]
I agree. Maybe it could have its own demo site builder.

**Comment by psychemedia** [comment]
I had a quick go at installing packages into `xeus-python-kernel` and failed to get it working, so I'm obviously missing a trick somewhere. Not sure I put the config file in the correct location / used correct config file name,  structure, etc.

**Comment by jtpio** [comment]
@psychemedia there are a couple of examples out there using the xeus python kernel with `jupyterlite_sphinx`. Otherwise a recent one with a deployment to GitHub Pages: https://github.com/jtpio/euroscipy-2022-jupyterlite-emscripten-forge 

Also if you would like to share a link to a repo that could be useful.

**Comment by martinRenou** [comment]
Closing as I believe the https://github.com/jupyterlite/xeus-python-demo repository resolves this issue. Please feel free to reopen if you believe otherwise.

**Comment by psychemedia** [comment]
@martinRenou template repo really useful, thanks..
